### PR TITLE
Resolves #399 (API Get objects using filter doesn't work)

### LINKED ISSUE #399: API Get objects using filter doesn't work.
https://github.com/csc/Hanlon/wiki/Hanlon-API-Overview#get-objects-using-filter

When I get simple model object by name attribute or policy object by label, it don't raise an error but hanlon return all objects.

I tested with my browser http://hanlonsrv:8026/hanlon/api/v1/model?name=test, it return all models, and it's the same way with curl and ruby script.
curl -X GET "http://hanlonsrv:8026/hanlon/api/v1/model?name=test"
and 
$uri=http://hanlonsrv:8026/hanlon/api/v1/model?name=test (for ruby script).

Is functionality deprecated or limited? If not, can you give me a working example please.

### PR DESCRIPTION
**Pull request by tjmcs**
The changes in this PR add an optional `filter_str` parameter to the `GET` methods of the RESTful APIs for the set of slices that are meant to be invoked by Hanlon users. Users can use this `filter_str` parameter to filter the set of object references (URIs) that will be returned from the `GET` operation to just those that. This new filter query parameter was added to the following endpoints:

* /active_model
* /broker
* /image
* /model
* /node
* /policy
* /tag
* tag/{UUID}/matcher

The value for the `filter_str` parameter is assumed to be a URI-encoded string (since it appears as part of the URI for the `GET`), and the value is assumed to be one or more `name=value` pairs separated by a `+` character. The result of the `GET` operation is then searched for objects who's `name` parameter matches the value specified.  Searches of nested (Hash maps) in the result are supported using a 'dot-separated' form for the name, so the `macaddress` parameter from the `attributes_hash` hash map contained in the output of a `GET` against the `node` slice (for example), can be compared to the fixed string `D2:7B:42:3B:33:D9` using an expression that looks like this:
```
attributes_hash.macaddress=D2:7B:42:3B:33:D9
```
Note that the dot between these two fields indicates that there should be a hash map under the `attributes_hash` key in the response object, and that there should be a `macaddress` field in that `attributes_hash` hash map. If a 'dot-separated' form is not provided, then the field is assumed to be available under the key 'name' in the response object itself.

There is also fairly complex structure that can be utilized in the `value` is being used to filter down the result set. The `values` can take any one of the following forms:

* A fixed string; in this case, a direct string comparison will be made to determine if the named parameter from the object matches the value in the `filter_str` (eg. `status=bound`)
* A string with the prefix `regex:`; in this case, a regular expression match will be attempted between the named parameter and the value provided in the `filter_str` (eg. `os_name=regex:^coreos`)
* An `&` or `|` separated set of fixed strings; in this case, the value will be split into an array of fixed strings, and a comparison between the named parameter and at array will be made to determine if a match exists (eg. `tags=small_disk&nics_1`). The rules for matching in this case depend on the type of field found in the result set under the named parameter (the '&' character is only valid for use when comparing with a named field that references an array of strings, for example, and will only match if **all** of the substrings in the value included in the `&` separated value are also contained in the array referenced by the named field, while an `|` separated set of substrings will match if there are **any** strings in common between the referenced array from the result set and the filter_str value.  If the referenced field from the result set is a string, then an `|` separated value can be used to search for objects where the referenced field matches **any** of the substrings in that `|` separated value.

It should also be noted here that if the value passed in is either a fixed string or a regular expression and the referenced field from the result set is an array, the object will be considered to match if the regular expression or fixed string from the filter_str matches at least one of the values in that array.

With these simple rules in mind, users can construct fairly complex `filter_str` values for their queries to subset the list of Hanlon objects returned in response to a `GET` against the top-level endpoints for these slices. In all cases, attempts are made to catch and report errors (in parsing or in matching) as they occur).

### CODE REVIEW

File: web/api/api_utils.rb [hunk 1]
```diff
@@ -54,6 +54,217 @@ def get_data
...
+        # but also contains the string 'regex:' (we don't support logical AND or logical OR matching
+        # via substrings that are, themselves, regular expressions)
+        raise ProjectHanlon::Error::Slice::InputError, "Illegal comparison_value; the declared value contains regular expressions as substrings" if comparison_regex && (and_sep_substrings || or_sep_substrings)
+        # throw an error if we're using an '&' separated set of substrings for our comparison_value
+        # but the object_value is not an array (the '&' separated substring construct only makes
+        # sense in the case of array comparisons)
+        raise ProjectHanlon::Error::Slice::InputError, "Illegal comparison_value; '&' separated strings cannot be compared to a non-Array object" if and_sep_substrings && !(object_value.is_a?(Array))
+        # Ensure that the elements of the object_value are converted to a string (if the
+        # object_value is an Array)
+        object_value.map { |val| val.to_s } if object_value.is_a?(Array)
```
Comment (jcpowermac) [inline web/api/api_utils.rb]: Should be a `map!`

File: web/api/api_utils.rb [hunk 2]
```diff
@@ -54,6 +54,217 @@ def get_data
...
+        # then, expand the response values to construct a corresponding array
+        # of objects that we can test for matches to the comparison hash
+        expanded_response = response.map { |response_elem|
+          if response_elem.has_key?("@uri")
+            uri = URI.parse response_elem["@uri"]
+            http = Net::HTTP.new(uri.host, uri.port)
+            request = Net::HTTP::Get.new(uri.request_uri)
+            lcl_response = http.request(request)
+            JSON.parse(lcl_response.body)["response"]
+          else
```
Comment (jcpowermac) [inline web/api/api_utils.rb]: No catch if there is an error.

File: web/api/api_utils.rb [hunk 3]
```diff
@@ -54,6 +54,217 @@ def get_data
...
+        or_sep_substrings = comparison_value.split('|') if comparison_value.include?('|')
+        and_sep_substrings = comparison_value.split('&') if comparison_value.include?('&')
+        # throw an error if both '&' and '|' characters were used in the declared comparison_value string
+        # (this method will match based on either a logical AND or a logical OR against the substrings in
+        # the comparison_value string, but not both)
+        raise ProjectHanlon::Error::Slice::InputError, "Illegal comparison_value; the declared value contains both '&' and '|' separated Strings" if and_sep_substrings && or_sep_substrings
+        # throw an error if the comparison_value contains a set of '&' or '|' separated substrings
+        # but also contains the string 'regex:' (we don't support logical AND or logical OR matching
+        # via substrings that are, themselves, regular expressions)
+        raise ProjectHanlon::Error::Slice::InputError, "Illegal comparison_value; the declared value contains regular expressions as substrings" if comparison_regex && (and_sep_substrings || or_sep_substrings)
```
Comment (jcpowermac) [inline web/api/api_utils.rb]: Needs to check if regular expression in side sub-string.

**Comment by jcpowermac** [comment]
Code review with @tjmcs.

File: web/api/api_utils.rb (hunk 2 above)
Comment (tjmcs) [inline web/api/api_utils.rb]: added code to raise an error in this case (shouldn't happen, but you never know)

**Comment by tjmcs** [comment]
Changes in the latest commit should fix the issues uncovered in my code review with @jcpowermac; PR is once again ready for review/approval

**Comment by mtnbikenc** [comment]
Code review :+1:

**Comment by jcpowermac** [comment]
Code Review :+1:
