### PR TITLE
Fixes #409 (Add error handling to new 'microkernel add' code)

### LINKED ISSUE #409: Add error handling to new 'microkernel add' code
The new code included in PR #404 that is used to add Docker-based Microkernel images to a
Hanlon Microkernel image includes coded that parses the underlying Docker image to obtain the
version information for the Hanlon Microkernel being added (from the tag associated with that image).
Once that PR is merge, a second PR should be submitted in short order to catch a number of possible
edge cases that could result in Exceptions and/or Errors being thrown that could (potentially) crash the
Hanlon server. Specifically:

* Code should be added to catch the case where a bzipped tarfile is passed into Hanlon via a
`hanlon image add -t mk ...` command, or the RESTful equivalent, but the `bzip2` gem is not available
locally on the Hanlon server
* Code should be added to catch the case where a bzipped or gzipped file was passed into Hanlon
but the file that was bzipped or gzipped is not a tarfile
* Code should be added to catch the case where a bzipped or gzipped tarfile was passed into Hanlon
but that tarfile is not actually a Docker image (in which case, the underlying code to parse the
`repositories` file from that tarfile might fail or the `repositories` file might not even exist in the tarfile)

other edge cases might exist, but these are the three edge cases that immediately come to mind
based on the structure of the underlying code being added in PR #404.

### PR DESCRIPTION
**Pull request by tjmcs**
This PR adds error handling to the new `hanlon image add` code (so that errors are caught and reported properly to CSC). Feedback is welcome!

### CODE REVIEW

File: core/slice/image.rb [hunk 1]
```diff
@@ -352,11 +366,47 @@ def get_docker_version_info(docker_image, zip_method = nil)
...
+               # if we found a JSON string containing a hash where the first value is a Hash we're on the right track.
+               # As such, if we get this far, then take the first key from the first value and return that as the version
+               # for the docker image file
+               version = first_value.keys[0]
+             rescue JSON::ParserError => e
+               # if we get here, then we weren't able to parse the 'repositories' entry as a JSON string, so it's
+               # not a Docker image; throw an appropriate error
+               raise ProjectHanlon::Error::Slice::InputError, "does not contain a Docker image ('repositories' entry cannot be parsed as a JSON string)"
+             end
+             semantic_versioned_image = true if version && /^[\d]+.[\d]+.[\d]+/.match(version)
```
Comment (Suirtimed) [inline core/slice/image.rb]: There is a semantic rubygem that might be a better choice for determining whether or not an image version is a valid semantic version identifier.  I believe this will highlight the regex they are using https://github.com/jlindsey/semantic/blob/master/lib/semantic/version.rb#L4

**Comment by Suirtimed** [comment]
In general, these all look to be good additions to error handling :+1:

**Comment by tjmcs** [comment]
The issue is with the string format that can be used for tagging the Docker container. We used to version the Microkernel using a string that was completely compliant with the semantic versioning spec, in which case the regex you mention above would work perfectly. Here's an example of a version string that meets that spec:
```
2.0.1-13-g3eade33-dirty
```
and here's a bit of output from an `irb` session that shows that string matching the regex from the code snippet you mentioned, @Suirtimed:
```
2.2.3 :001 > /\A(\d+\.\d+\.\d+)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?\Z/.match('2.0.1-13-g3eade33-dirty')
 => #<MatchData "2.0.1-13-g3eade33-dirty" 1:"2.0.1" 2:"-13-g3eade33-dirty" 3:"13-g3eade33-dirty" 4:nil 5:nil 6:nil 7:nil>
2.2.3 :002 >
```
but that version string cannot be used as a tag for a Docker image, so we've switched over to using a version string that looks like this instead (which we can use as a Docker image tag):
```
2.0.1_13-g3eade33-dirty
```
and that string fails to match the regex you mentioned because of the shift from an `_` to a `-` between the build number and the rest of the version string. So we could take any of the following approaches:

* leave the code as-is
* modify the Hanlon to map that `_` to a `-` when the tag is parsed out of the Docker image and then use the remapped version string internally (would require a few other changes, but is entirely possible), then use the regex you pointed to instead of the one we defined internally
* modify the regex you mentioned earlier to include the `_` character instead of the `-` character and make a note of why we're not using a standard regex to parse our pseudo-semantic version string

Thoughts on which would be a better approach?

**Comment by Suirtimed** [comment]
I think in this case, attempting to keep things simple is the better approach.  I doubt we're going to convince the docker community to change the syntax for naming a docker image to match a semver string pattern.  I think I'd leave the code as is with a comment for future generations of maintainers to ponder.

**Comment by jcpowermac** [comment]
Code review with @tjmcs :+1:
